name: Golang with cache
author: Peter Mescalchin
description: Setup requested Golang version with enabled module and build caching.

inputs:
  go-version:
    description: The desired Go version to use.
    required: true
  cache-key-suffix:
    description: Optional cache key suffix.
    default:

runs:
  using: composite
  steps:
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}
    - name: Determine Golang cache paths
      id: golang-path
      run: |
        echo "::set-output name=build::$(go env GOCACHE)"
        echo "::set-output name=module::$(go env GOMODCACHE)"
      shell: bash
    - name: Setup Golang cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ steps.golang-path.outputs.build }}
          ${{ steps.golang-path.outputs.module }}
        key: ${{ runner.os }}-golang${{ inputs.cache-key-suffix }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang${{ inputs.cache-key-suffix }}-
